
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/Cheese.pnct \
    $(DIST)/Cheese.scene \

$(DIST)/Cheese.scene : Cheese.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "Cheese.blend:Main" "$(DIST)/Cheese.scene"

$(DIST)/Cheese.pnct : Cheese.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "Cheese.blend:Main" "$(DIST)/Cheese.pnct" 
